# Docker Compose file for development

services:
  pi-vpn:
    build: .
    container_name: pi-vpn-dev
    restart: unless-stopped
    privileged: true
    volumes:
      - .:/app
      - /etc/wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "3000:3000"
      - "51820:51820/udp"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=dev-secret-key-change-in-production
      - VPN_INTERFACE=wg0
      - VPN_PORT=51820
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    command: ["npm", "run", "dev"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development database (optional)
  redis:
    image: redis:alpine
    container_name: pi-vpn-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    profiles:
      - with-redis

volumes:
  redis-data:
    driver: local